services:
  - type: web
    name: educator-app-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      # Environment variables will need to be set manually in Render dashboard:
      # DATABASE_URL, DB_USER, DB_PASSWORD, DB_HOST, DB_DATABASE, DB_PORT
      # JWT_SECRET, GEMINI_API_KEY, GLOT_API_KEY, etc.