-- =================================================================
-- ESSAY MENTOR AI INTEGRATION: Add Essay Subscription Fields
-- =================================================================
-- Adds fields to the users table to track essay generation quota
-- and subscription status for the EssayMentor AI system

BEGIN;

-- Add essay subscription and tracking fields to users table
ALTER TABLE users
ADD COLUMN IF NOT EXISTS subscription_tier VARCHAR(20) DEFAULT 'free' CHECK (subscription_tier IN ('free', 'monthly', 'annual')),
ADD COLUMN IF NOT EXISTS free_essays_used INTEGER DEFAULT 0 CHECK (free_essays_used >= 0),
ADD COLUMN IF NOT EXISTS essays_generated INTEGER DEFAULT 0 CHECK (essays_generated >= 0),
ADD COLUMN IF NOT EXISTS subscription_ends_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS student_profile JSONB DEFAULT '{}';

-- Create index for efficient quota checking
CREATE INDEX IF NOT EXISTS idx_users_subscription_tier ON users(subscription_tier);
CREATE INDEX IF NOT EXISTS idx_users_essays_generated ON users(essays_generated);

-- Add comment for documentation
COMMENT ON COLUMN users.subscription_tier IS 'Essay generation subscription tier: free (2 essays), monthly, or annual';
COMMENT ON COLUMN users.free_essays_used IS 'Number of free essays used (max 2 for free tier)';
COMMENT ON COLUMN users.essays_generated IS 'Total number of essays generated by this user';
COMMENT ON COLUMN users.subscription_ends_at IS 'Subscription expiration date (NULL for free tier)';
COMMENT ON COLUMN users.student_profile IS 'Student profile for essay personalization (name, background, experiences, SAT verbal, voice characteristics)';

COMMIT;

-- Sample query to check if user can generate essay:
-- SELECT
--   id,
--   subscription_tier,
--   free_essays_used,
--   CASE
--     WHEN subscription_tier = 'free' AND free_essays_used < 2 THEN TRUE
--     WHEN subscription_tier IN ('monthly', 'annual') AND subscription_ends_at > NOW() THEN TRUE
--     ELSE FALSE
--   END as can_generate_essay
-- FROM users
-- WHERE id = $1;
